10_Django/ch02_wordcnt/ch02_wordcnt/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from django.conf.urls import url
import home.views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    path('test/',views.test, name='test'),
    path('showId/<int:id>/', views.intId, name="showIntId"),
    path('showId/<str:id>/', views.strId, name="showStrId"),
    path('wordcnt/', include('wordcnt.urls')),
]

10_Django/ch02_wordcnt/wordcnt/urls.py
from django.urls import path
import wordcnt.views

app_name= "wordcnt"

urlpatterns=[
    path("", wordcnt.views.wordinput, name="wordinput"),
    path('result/', wordcnt.views.result, name="result"),
    path('about/', wordcnt.views.about, name="about")
]

10_Django/ch02_wordcnt/home/models.py
from django.db import models

# Create your models here.

10_Django/ch02_wordcnt/wordcnt/models.py
from django.db import models

# Create your models here.

10_Django/ch02_wordcnt/home/views.py
from django.shortcuts import render

from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

def index(request):
    msg = "My massage는 Hello, Django !"
    return render(request, 'home/index.html', {'msg': msg})


def test(request):
    return HttpResponse('<h1 style="color:red;">테스트</h1><h2>페이지</h2>')


def intId(request, id):
    msg = '숫자 ID는 ' + str(id)
    idtype = '숫자'
    return render(request, 'home/showId.html', {'msg': msg, 'type': idtype})


def strId(request, id):
    msg = '문자 ID는 ' + id
    idtype = '숫자'
    return render(request, 'home/showId.html', {'msg': msg, 'type': idtype})

10_Django/ch02_wordcnt/wordcnt/views.py
from django.shortcuts import render


# Create your views here.


def wordinput(request):
    return render(request, "wordinput.html")


def result(request):
    full = request.GET['fulltext'] #안녕 방가 안녕
    strlength = len(full)
    words= full.split() # ['안녕', '방가', '안녕']
    words_dic = {} #{'안녕':,'방가':1}
    for word in words:
        if word in words_dic:
            words_dic[word] += 1
        else:
            words_dic[word] = 1
    return render(request, 'result.html',{'full':full,
                                         'strlength':strlength,
                                         'cnt':len(words),
                                         'dic':words_dic.items()})

def about(request):
    return render(request, "about.html")

10_Django/ch02_wordcnt/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    {% load static %}
    <link href="{% static 'css/ex.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <h2>템플릿을 사용해 보았어요</h2>
    <h1>view에서 받은 msg : {{msg}}</h1>
    <img src="{% static 'image/django.png' %}" alt="안 가져옴"><br>
    <a href="{% url 'test' %}">TEST로 가기</a>
    <button type="button" class="btn btn-success"
        onclick="location.href='{% url 'test' %}'">TEST로 가기</button>
    <a href="showId/123">SHOW 123 ID</a>
    <a href="showId/ABC">SHOW ABC ID</a>
    <a href="{% url 'showStrId' 'ABC' %}">SHOW ABC ID</a>
    <a href="wordcnt">글자 수 세기</a>
</body>
</html>

10_Django/ch02_wordcnt/home/templates/home/showId.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link href="{% static 'css/ex.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <h1>render함수를 이용해서 템플릿(client가 보는 화면)사용</h1>
    <h2> 입력하신 ID타입은 {{type}}</h2>
    <h2>{{msg}}</h2>
    <a href="">index(처음)로 가기</a>
</body>
</html>

10_Django/ch02_wordcnt/wordcnt/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link href="{% static 'css/ex.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <h1> 글자 수, 단어 수 세고 각 단어별 출현 횟수 출력</h1>
    <a href="{%url 'wordcnt:wordinput'%}">글자입력</a>
</body>
</html>

10_Django/ch02_wordcnt/wordcnt/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link href="{% static 'css/ex.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <h1> 글자수: {{strlength}}</h1>
    <h2> 단어수: {{cnt}} </h2>
    <h2> 입력한 텍스트: {{full}}</h2>
    <h2> 단어 카운트 결과 </h2>
    <% for key, value in dic %>
        <span> {{key}}</span>: {{value}}<br>
    <% endfor %>
    <a href="{% url 'wordcnt:wordinput' %}"> 글자 다시 입력하기</a>
</body>
</html>

10_Django/ch02_wordcnt/wordcnt/templates/wordinput.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link href="{% static 'css/ex.css' %}" rel="stylesheet" type="text/css">

</head>
<body>
    <h1> 단어와 글자 수 세기 프로그램 </h1>
    <h3> <a href="{% url 'wordcnt:about' %}">자세한 도움말은 about</a></h3>
    <form action="{% url 'wordcnt:result' %}" method="get">
        <textarea name="fulltext" cols="30" rows="3"> </textarea>
        <input type="submit" value="계산">
    </form>
</body>
</html>