10_Django/ch04_haksa/ch04_haksa/urls.py
from django.contrib import admin
from django.urls import path, include
import students.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('', students.views.listAll, name="home")
]

10_Django/ch04_haksa/students/urls.py
from django.urls import path
from . import views

app_name = "students"
urlpatterns = [
    path("listAll/", views.listAll, name='listAll'),
    path('register/', views.registerStudent, name='register'),
    path('registerCon/', views.registerConStudent, name='registerCon'),
    path('detail/<str:name>/', views.detailStudent, name='detail'),
    path('modify/<str:name>/', views.modifyStudent, name='modify'),
    path('modifyCon/', views.modifyConStudent, name='modifyCon'),
    path('delete/<str:name>', views.deleteStudent, name='delete'),
]

10_Django/ch04_haksa/students/models.py
from django.db import models


class Student(models.Model):
    s_name = models.CharField(max_length=1000)
    s_major = models.CharField(max_length=100)
    s_age = models.IntegerField(default=0)
    s_grade = models.IntegerField(default=0)
    s_gender = models.CharField(max_length=30)

    def __str__(self):
        return "{} ({},{},{}살,{}".format(self.s_name, self.s_major, self.s_grade, self.s_age, self.s_gender)

10_Django/ch04_haksa/students/views.py
from django.shortcuts import render
from students.models import Student
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.shortcuts import redirect


# 학생목록

def listAll(request):
    qs = Student.objects.all()
    context = {'student_list': qs}
    return render(request, 'students/studentListAll.html', context)


# 학생 등록

def registerStudent(request):
    return render(request, 'students/registerStudent.html')


# 학생등록 입력받아 db저장

def registerConStudent(request):
    name = request.POST['name']
    major = request.POST['major']
    age = request.POST['age']
    grade = request.POST['grade']
    gender = request.POST['gender']
    qs = Student(s_name=name, s_major=major, s_age=age, s_grade=grade, s_gender=gender)
    qs.save()
    return HttpResponseRedirect(reverse('students:listAll'))


def detailStudent(request, name):
    try:
        qs = Student.objects.get(s_name=name)
    except:
        qs = Student.objects.filter(s_name__contains=name)
    context = {'student': qs}
    return render(request, 'students/detailStudent.html', context=context)


# 학생 수정
def modifyStudent(request, name):
    try:
        qs = Student.objects.get(s_name=name)
    except:
        qs = ''
    context = {'student': qs}
    return render(request, 'students/modifyStudent.html', context=context)


# 수정 con
def modifyConStudent(request):
    name = request.POST['name']
    major = request.POST['major']
    age = request.POST['age']
    grade = request.POST['grade']
    gender = request.POST['gender']
    qs = Student.objects.get(s_name=name)
    qs.s_major = major
    qs.s_age = age
    qs.s_grade = grade
    qs.s_gender = gender
    qs.save()
    return HttpResponseRedirect(reverse('students:listAll'))


def deleteStudent(request, name):
    try:
        qs = Student.objects.get(s_name=name)
        qs.delete()
        print(name, '삭제성공')
    except:
        print(name, '삭제 실패')
    return redirect('/students/listAll')

10_Django/ch04_haksa/students/templates/students/detailStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>상세보기</title>
    {% load static %}
    <link href = "{% static 'style.css'%}" rel="stylesheet" type="text/css">
</head>
<body>
    <table>
        <caption> 상세보기 </caption>
        {% if student %}
            <tr><th>이름</th><td>{{student.s_name}}</td></tr>
            <tr><th>전공</th><td>{{student.s_major}}</td></tr>
            <tr><th>나이</th><td>{{student.s_age}}</td></tr>
            <tr><th>학년</th><td>{{student.s_grade}}</td></tr>
            <tr><th>성별</th><td>{{student.s_gender}}</td></tr>
            <tr>
                <td colspan = "2">
                    <button onclick = "location = '{% url 'students:modify' student.s_name%}'"> 수정</button>
                    <button onclick = "location = '{% url 'students:delete' student.s_name%}'"> > 삭제</button>
                    <button onclick = "location = '{% url 'students:listAll' %}'"> > 목록</button>
                </td>
            </tr>
        {% else %}
            <tr><th>없는 데이터입니다.</th></tr>
            <tr>
                <td>
                    <button onclick = "lcoation = '/students/listAll'"> 목록</button>
                    <button onclick = "lcoation = '{% url 'students:listAll' %}'"> 목록</button>
                </td>
            </tr>
        {% endif %}
    </table>
</body>
</html>

10_Django/ch04_haksa/students/templates/students/modifyStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>상세보기</title>
    {% load static %}
    <link href = "{% static 'style.css'%}" rel="stylesheet" type="text/css">
</head>
<body>
<form action = "{%url 'students:modifyCon' %}" method="post">
    {% csrf_token %}
    <table>
        <caption> 상세보기 </caption>
        {% if student %}
            <tr><th>이름</th>
                <td>
                    <input type = "text" name = "name" value="{{student.s_name}}"
                           readonly="readonly">
                </td>
            </tr>
            <tr><th>전공</th>
                <td>
                    <input type = "text" name = "major" value="{{student.s_major}}" autofocus="autofocus">
                </td>
            </tr>
            <tr><th>나이</th>
                <td>
                    <input type = "number" name = "age" value="{{student.s_age}}">
                </td>
            </tr>
            <tr><th>학년</th>
                <td>
                    <input type = "number" name = "grade" value="{{student.s_grade}}">
                </td>
            </tr>
            <tr><th>성별</th>
                <td>
                    {% if student.s_gender == '남' %}
                        <input type ="radio" name="gender" value = "남" checked="checked">남
                        <input type ="radio" name="gender" value = "여">여
                    {% else %}
                        <input type ="radio" name="gender" value = "남">남
                        <input type ="radio" name="gender" value = "여" checked="checked">여
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td colspan = "2">
                    <input type="submit" value = "수정" onclick = "location='{% url 'students:modify' student.s_name%}'">
                    <input type="submit" value = "삭제" onclick = "location='#삭제url'">
                    <input type="button" value = "목록" onclick = "location ='{%url 'students:listAll'%}'">
                    <input type="button" value="등록" onclick = "location ='/students/register'">
                </td>
            </tr>
        {% else %}
            <tr><th>없는 데이터입니다.</th></tr>
            <tr>
                <td>
                    <button onclick = "lcoation = '/students/listAll'"> 목록</button>
                    <button onclick = "lcoation = '{% url 'students:listAll' %}'"> 목록</button>
                </td>
            </tr>
        {% endif %}
    </table>
</form>
</body>
</html>

10_Django/ch04_haksa/students/templates/students/registerStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link href = "{% static 'style.css'%}" rel="stylesheet" type="text/css">
</head>
<body>
    <form action="{% url 'students:registerCon' %}" method = "post">
        {% csrf_token %}
        <table>
            <tr><th>이름</th><td><input type="text" name="name"></td></tr>
            <tr><th>전공</th><td><input type="text" name="major"></td></tr>
            <tr><th>나이</th><td><input type="number" name="age" min="0"></td></tr>
            <tr><th>학년</th><td><input type="number" name="grade"></td></tr>
            <tr><th>성별</th><td>
                <input type = "radio" name="gender" value = "남" checked = "checked">남
                <input type = "radio" name="gender" value = "여">여
            </td></tr>
            <tr>
                <td colspan="2">
                    <input type = "submit" value = "학생등록">
                    <input type = "button" value = "학생목록"
                           onclick = "location='/students/listAll'">
                    <input type = "button" value = "학생목록"
                           onclick = "location='{% url 'students:listAll' %}'">

                </td>
            </tr>

        </table>
    </form>
</body>
</html>

10_Django/ch04_haksa/students/templates/students/studentListAll.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>학생들 리스트</title>
    {% load static %}
    <link href = "{% static 'style.css'%}" rel="stylesheet" type="text/css">
</head>
<body>
    <table>
        <caption>student list</caption>
        <tr><th colspan = "4"><a href = "{% url 'students:register' %}">< 신규 학생 등록></a></th></tr>
        <tr><th>이름</th><th>전공</th><th>학년</th><th>수정 및 삭제</th></tr>
        {% if student_list %}
            {% for student in student_list %}
            <tr>
                <td><a href = "{% url 'students:detail' student.s_name %}">{{student.s_name}}</a></td>
                <td>{{student.s_major}}</td>
                <td>{{student.s_grade}}</td>
                <td>
                    <button onclick = "location = '{% url 'students:modify' student.s_name%}'">수정</button>
                    <button onclick = "location = '{% url 'students:delete' student.s_name%}'">삭제</button>
                </td>
            </tr>
            {% endfor %}
        {% else %}
            <tr><th colspan = "4"> Student : 현재 0명 </th></tr>
        {% endif %}
    </table>
</body>
</html>